### ISSUE TITLE
Move ANN code to a .py file

### ISSUE THREAD

**Issue by DanielYakubov** [DanielYakubov/Phish-Sight-replication#15]
# Problem

I think it is a little bad practice to have both notebooks and .py files in the same repo that serve the same purpose, so I removed all the notebooks from the main branch. They are still accessible on `notebook-branch`. After doing this, I realized this removed the ANN code.

# Tasks

- [ ] Port ANN code from jupyter notebook on `notebook-branch` to a .py file on the main branch 
- [ ] Heavily document it using google style doc strings

**Comment by DanielYakubov** [comment]
@Lewy09-Tm25 Are you okay with me handling this? It is your code so I wasn't sure if you wanted to bring the ANN code over yourself.

**Comment by Lewy09-Tm25** [comment]
@DanielYakubov I agree with your approach. I am totally fine if you handle this.
